
import __ASTRO_IMAGE_IMPORT_Z25ClNo from "@assets/hero/avatar.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fhero%2Findex.yaml";
import __ASTRO_IMAGE_IMPORT_Z1bVxEs from "@assets/about/photo.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fabout%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z2cwm9C from "@assets/blog/embed-examples/image.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fembed-examples.mdoc";
import __ASTRO_IMAGE_IMPORT_Z1SXK34 from "@assets/blog/blog_post.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwelcome-post.md";
import __ASTRO_IMAGE_IMPORT_Z1AfM43 from "@assets/blog/guides/content-collections-guide/image.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fguides%2Fcontent-collections-guide.mdoc";
import __ASTRO_IMAGE_IMPORT_1h60LA from "@assets/blog/guides/markdown-guide/image.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fguides%2Fmarkdown-guide.mdoc";
import __ASTRO_IMAGE_IMPORT_29x53L from "@assets/blog/guides/bloomfolio-complete-guide-building-your-portfolio/image.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fguides%2Fbloomfolio-complete-guide-building-your-portfolio.mdoc";
export default new Map([["@assets/hero/avatar.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fhero%2Findex.yaml", __ASTRO_IMAGE_IMPORT_Z25ClNo], ["@assets/about/photo.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fabout%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1bVxEs], ["@assets/blog/embed-examples/image.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fembed-examples.mdoc", __ASTRO_IMAGE_IMPORT_Z2cwm9C], ["@assets/blog/blog_post.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwelcome-post.md", __ASTRO_IMAGE_IMPORT_Z1SXK34], ["@assets/blog/guides/content-collections-guide/image.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fguides%2Fcontent-collections-guide.mdoc", __ASTRO_IMAGE_IMPORT_Z1AfM43], ["@assets/blog/guides/markdown-guide/image.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fguides%2Fmarkdown-guide.mdoc", __ASTRO_IMAGE_IMPORT_1h60LA], ["@assets/blog/guides/bloomfolio-complete-guide-building-your-portfolio/image.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fguides%2Fbloomfolio-complete-guide-building-your-portfolio.mdoc", __ASTRO_IMAGE_IMPORT_29x53L]]);
		